import { useMemo } from 'react';

export const ThemeColors = (theme: string, isDarkMode: boolean) => {
  const colorSchemes = {
    cyberpurple: {
      dark: 'bg-gradient-to-b from-[#2a1a5e] via-[#3b2a8f] to-[#6a4db8]',
      light: 'bg-gradient-to-b from-[#f5efff] via-[#f0e5ff] to-[#e3d5ff]',
      headerDark: 'bg-gradient-to-r from-[#2a1a5e] via-[#3b2a8f] to-[#6a4db8]',
      headerLight: 'bg-gradient-to-r from-[#f5efff] via-[#f0e5ff] to-[#e3d5ff]',
      border: 'border-[#e879f9]',
      textDark: 'text-[#e879f9]',
      textLight: 'text-[#7e22ce]',
      hoverDark: 'hover:text-[#f0abfc]',
      hoverLight: 'hover:text-[#a855f7]',
      buttonDark: 'bg-[#7e22ce] hover:bg-[#e879f9]',
      buttonLight: 'bg-[#e879f9] hover:bg-[#d946ef]',
      dropdownBgDark: 'bg-[#3b2a8f]',
      dropdownBgLight: 'bg-[#f5efff]',
      dropdownBorder: 'border-[#e879f9]',
      dropdownTextDark: 'text-[#e879f9]',
      dropdownTextLight: 'text-[#7e22ce]',
      glow: '#e879f9',
      accentDark: 'bg-[#e879f9]/30',
      accentLight: 'bg-[#a855f7]/30',
      primaryDark: 'text-[#f0abfc]',
      primaryLight: 'text-[#a855f7]',
      secondaryDark: 'border-[#f0abfc]',
      secondaryLight: 'border-[#a855f7]',
      particleColors: {
        backgroundDark: '#2a1a5e',
        backgroundLight: '#f5efff',
        particleDark: '#e879f9',
        particleLight: '#7e22ce',
      },
    },
    neonblue: {
      dark: 'bg-gradient-to-b from-[#1e3a8a] via-[#2563eb] to-[#3b82f6]',
      light: 'bg-gradient-to-b from-[#e0f7fa] via-[#dbeafe] to-[#bfdbfe]',
      headerDark: 'bg-gradient-to-r from-[#1e3a8a] via-[#2563eb] to-[#3b82f6]',
      headerLight: 'bg-gradient-to-r from-[#e0f7fa] via-[#dbeafe] to-[#bfdbfe]',
      border: 'border-[#60a5fa]',
      textDark: 'text-[#60a5fa]',
      textLight: 'text-[#2563eb]',
      hoverDark: 'hover:text-[#93c5fd]',
      hoverLight: 'hover:text-[#3b82f6]',
      buttonDark: 'bg-[#2563eb] hover:bg-[#60a5fa]',
      buttonLight: 'bg-[#60a5fa] hover:bg-[#3b82f6]',
      dropdownBgDark: 'bg-[#1e3a8a]',
      dropdownBgLight: 'bg-[#e0f7fa]',
      dropdownBorder: 'border-[#60a5fa]',
      dropdownTextDark: 'text-[#60a5fa]',
      dropdownTextLight: 'text-[#2563eb]',
      glow: '#60a5fa',
      accentDark: 'bg-[#60a5fa]/30',
      accentLight: 'bg-[#3b82f6]/30',
      primaryDark: 'text-[#93c5fd]',
      primaryLight: 'text-[#3b82f6]',
      secondaryDark: 'border-[#93c5fd]',
      secondaryLight: 'border-[#3b82f6]',
      particleColors: {
        backgroundDark: '#1e3a8a',
        backgroundLight: '#e0f7fa',
        particleDark: '#60a5fa',
        particleLight: '#2563eb',
      },
    },
    electricpink: {
      dark: 'bg-gradient-to-b from-[#3b1a4a] via-[#7c2d6a] to-[#c11f8a]',
      light: 'bg-gradient-to-b from-[#ffe4f5] via-[#ffceec] to-[#ffb1de]',
      headerDark: 'bg-gradient-to-r from-[#3b1a4a] via-[#7c2d6a] to-[#c11f8a]',
      headerLight: 'bg-gradient-to-r from-[#ffe4f5] via-[#ffceec] to-[#ffb1de]',
      border: 'border-[#f9a8d4]',
      textDark: 'text-[#f9a8d4]',
      textLight: 'text-[#be185d]',
      hoverDark: 'hover:text-[#fbcfe8]',
      hoverLight: 'hover:text-[#ec4899]',
      buttonDark: 'bg-[#be185d] hover:bg-[#f9a8d4]',
      buttonLight: 'bg-[#f9a8d4] hover:bg-[#ec4899]',
      dropdownBgDark: 'bg-[#3b1a4a]',
      dropdownBgLight: 'bg-[#ffe4f5]',
      dropdownBorder: 'border-[#f9a8d4]',
      dropdownTextDark: 'text-[#f9a8d4]',
      dropdownTextLight: 'text-[#be185d]',
      glow: '#f9a8d4',
      accentDark: 'bg-[#f9a8d4]/30',
      accentLight: 'bg-[#ec4899]/30',
      primaryDark: 'text-[#fbcfe8]',
      primaryLight: 'text-[#ec4899]',
      secondaryDark: 'border-[#fbcfe8]',
      secondaryLight: 'border-[#ec4899]',
      particleColors: {
        backgroundDark: '#3b1a4a',
        backgroundLight: '#ffe4f5',
        particleDark: '#f9a8d4',
        particleLight: '#be185d',
      },
    },
    cosmicteal: {
      dark: 'bg-gradient-to-b from-[#1e4045] via-[#2dd4bf] to-[#14b8a6]',
      light: 'bg-gradient-to-b from-[#ccfbf1] via-[#a5f3fc] to-[#5eead4]',
      headerDark: 'bg-gradient-to-r from-[#1e4045] via-[#2dd4bf] to-[#14b8a6]',
      headerLight: 'bg-gradient-to-r from-[#ccfbf1] via-[#a5f3fc] to-[#5eead4]',
      border: 'border-[#5eead4]',
      textDark: 'text-[#5eead4]',
      textLight: 'text-[#0d9488]',
      hoverDark: 'hover:text-[#99f6e4]',
      hoverLight: 'hover:text-[#2dd4bf]',
      buttonDark: 'bg-[#0d9488] hover:bg-[#5eead4]',
      buttonLight: 'bg-[#5eead4] hover:bg-[#2dd4bf]',
      dropdownBgDark: 'bg-[#1e4045]',
      dropdownBgLight: 'bg-[#ccfbf1]',
      dropdownBorder: 'border-[#5eead4]',
      dropdownTextDark: 'text-[#5eead4]',
      dropdownTextLight: 'text-[#0d9488]',
      glow: '#5eead4',
      accentDark: 'bg-[#5eead4]/30',
      accentLight: 'bg-[#2dd4bf]/30',
      primaryDark: 'text-[#99f6e4]',
      primaryLight: 'text-[#2dd4bf]',
      secondaryDark: 'border-[#99f6e4]',
      secondaryLight: 'border-[#2dd4bf]',
      particleColors: {
        backgroundDark: '#1e4045',
        backgroundLight: '#ccfbf1',
        particleDark: '#5eead4',
        particleLight: '#0d9488',
      },
    },
    solarorange: {
      dark: 'bg-gradient-to-b from #[2c2b19]',
      light: 'bg-gradient-to-b from-[#ffedd5] via-[#fed7aa] to #[fdba74]',
      headerDark: 'bg-gradient-to-r from-[#4c2b19] via-[#c2410c] to-[#ea580c]',
      headerLight: 'bg-gradient-to-r from-[#ffedd5] via-[#fed7aa] to-[#fdba74]',
      border: 'border-[#ff8c00]',
      textDark: 'text-[#ff8c00]',
      textLight: 'text-[#c2410c]',
      hoverDark: 'hover:text-[#ffbd59]',
      hoverLight: 'hover:text-[#ff4500]',
      buttonDark: 'bg-[#c2410c] hover:bg-[#ff8c00]',
      buttonLight: 'bg-[#ff8c00] hover:bg-[#ff4500]',
      dropdownBgDark: 'bg-[#4c2b19]',
      dropdownBgLight: 'bg-[#ffedd5]',
      dropdownBorder: 'border-[#ff8c00]',
      dropdownTextDark: 'text-[#ff8c00]',
      dropdownTextLight: 'text-[#c2410c]',
      glow: '#ff8c00',
      accentDark: 'bg-[#ff8c00]/30',
      accentLight: 'bg-[#ff4500]/30',
      primaryDark: 'text-[#ffbd59]',
      primaryLight: 'text-[#ff4500]',
      secondaryDark: 'border-[#ffbd59]',
      secondaryLight: 'border-[#ff4500]',
      particleColors: {
        backgroundDark: '#4c2b19',
        backgroundLight: '#ffedd5',
        particleDark: '#ff8c00',
        particleLight: '#c2410c',
      },
    },
    lunargreen: {
      dark: 'bg-gradient-to-b from-[#1e3a2a] via-[#22c55e] to-[#16a34a]',
      light: 'bg-gradient-to-b from-[#d9f99d] via-[#bef264] to-[#86efac]',
      headerDark: 'bg-gradient-to-r from-[#1e3a2a] via-[#22c55e] to-[#16a34a]',
      headerLight: 'bg-gradient-to-r from-[#d9f99d] via-[#bef264] to-[#86efac]',
      border: 'border-[#86efac]',
      textDark: 'text-[#86efac]',
      textLight: 'text-[#16a34a]',
      hoverDark: 'hover:text-[#bbf7d0]',
      hoverLight: 'hover:text-[#22c55e]',
      buttonDark: 'bg-[#16a34a] hover:bg-[#86efac]',
      buttonLight: 'bg-[#86efac] hover:bg-[#22c55e]',
      dropdownBgDark: 'bg-[#1e3a2a]',
      dropdownBgLight: 'bg-[#d9f99d]',
      dropdownBorder: 'border-[#86efac]',
      dropdownTextDark: 'text-[#86efac]',
      dropdownTextLight: 'text-[#16a34a]',
      glow: '#86efac',
      accentDark: 'bg-[#86efac]/30',
      accentLight: 'bg-[#22c55e]/30',
      primaryDark: 'text-[#bbf7d0]',
      primaryLight: 'text-[#22c55e]',
      secondaryDark: 'border-[#bbf7d0]',
      secondaryLight: 'border-[#22c55e]',
      particleColors: {
        backgroundDark: '#1e3a2a',
        backgroundLight: '#d9f99d',
        particleDark: '#86efac',
        particleLight: '#16a34a',
      },
    },
    starred: {
      dark: 'bg-gradient-to-b from-[#3b1a1a] via-[#b91c1c] to-[#dc2626]',
      light: 'bg-gradient-to-b from-[#fee2e2] via-[#fecaca] to-[#fca5a5]',
      headerDark: 'bg-gradient-to-r from-[#3b1a1a] via-[#b91c1c] to-[#dc2626]',
      headerLight: 'bg-gradient-to-r from-[#fee2e2] via-[#fecaca] to-[#fca5a5]',
      border: 'border-[#f87171]',
      textDark: 'text-[#f87171]',
      textLight: 'text-[#b91c1c]',
      hoverDark: 'hover:text-[#fca5a5]',
      hoverLight: 'hover:text-[#ef4444]',
      buttonDark: 'bg-[#b91c1c] hover:bg-[#f87171]',
      buttonLight: 'bg-[#f87171] hover:bg-[#ef4444]',
      dropdownBgDark: 'bg-[#3b1a1a]',
      dropdownBgLight: 'bg-[#fee2e2]',
      dropdownBorder: 'border-[#f87171]',
      dropdownTextDark: 'text-[#f87171]',
      dropdownTextLight: 'text-[#b91c1c]',
      glow: '#f87171',
      accentDark: 'bg-[#f87171]/30',
      accentLight: 'bg-[#ef4444]/30',
      primaryDark: 'text-[#fca5a5]',
      primaryLight: 'text-[#ef4444]',
      secondaryDark: 'border-[#fca5a5]',
      secondaryLight: 'border-[#ef4444]',
      particleColors: {
        backgroundDark: '#3b1a1a',
        backgroundLight: '#fee2e2',
        particleDark: '#f87171',
        particleLight: '#b91c1c',
      },
    },
    galacticgold: {
      dark: 'bg-gradient-to-b from-[#3b2f1a] via-[#b45309] to-[#d97706]',
      light: 'bg-gradient-to-b from-[#fefcbf] via-[#fde68a] to-[#fcd34d]',
      headerDark: 'bg-gradient-to-r from-[#3b2f1a] via-[#b45309] to-[#d97706]',
      headerLight: 'bg-gradient-to-r from-[#fefcbf] via-[#fde68a] to-[#fcd34d]',
      border: 'border-[#fde047]',
      textDark: 'text-[#fde047]',
      textLight: 'text-[#b45309]',
      hoverDark: 'hover:text-[#fef08a]',
      hoverLight: 'hover:text-[#eab308]',
      buttonDark: 'bg-[#b45309] hover:bg-[#fde047]',
      buttonLight: 'bg-[#fde047] hover:bg-[#eab308]',
      dropdownBgDark: 'bg-[#3b2f1a]',
      dropdownBgLight: 'bg-[#fefcbf]',
      dropdownBorder: 'border-[#fde047]',
      dropdownTextDark: 'text-[#fde047]',
      dropdownTextLight: 'text-[#b45309]',
      glow: '#fde047',
      accentDark: 'bg-[#fde047]/30',
      accentLight: 'bg-[#eab308]/30',
      primaryDark: 'text-[#fef08a]',
      primaryLight: 'text-[#eab308]',
      secondaryDark: 'border-[#fef08a]',
      secondaryLight: 'border-[#eab308]',
      particleColors: {
        backgroundDark: '#3b2f1a',
        backgroundLight: '#fefcbf',
        particleDark: '#fde047',
        particleLight: '#b45309',
      },
    },
  };

  return useMemo(() => ({
    colors: colorSchemes[theme as keyof typeof colorSchemes],
    particleColors: colorSchemes[theme as keyof typeof colorSchemes].particleColors,
  }), [theme, isDarkMode]);
};