import { useMemo } from 'react';

export const ThemeColors = (theme: string, isDarkMode: boolean) => {
  const colorSchemes = {
    cyberpurple: {
      dark: 'bg-gradient-to-b from-[#1e123f] via-[#2d1a5e] to-[#4c2889]',
      light: 'bg-gradient-to-b from-[#f3e8ff] via-[#ede9fe] to-[#ddd6fe]',
      headerDark: 'bg-gradient-to-r from-[#1e123f] via-[#2d1a5e] to-[#4c2889]',
      headerLight: 'bg-gradient-to-r from-[#f3e8ff] via-[#ede9fe] to-[#ddd6fe]',
      border: 'border-[#d946ef]',
      textDark: 'text-[#d946ef]',
      textLight: 'text-[#6b21a8]',
      hoverDark: 'hover:text-[#f472b6]',
      hoverLight: 'hover:text-[#9333ea]',
      buttonDark: 'bg-[#6b21a8] hover:bg-[#d946ef]',
      buttonLight: 'bg-[#d946ef] hover:bg-[#a855f7]',
      dropdownBgDark: 'bg-[#2d1a5e]',
      dropdownBgLight: 'bg-[#f3e8ff]',
      dropdownBorder: 'border-[#d946ef]',
      dropdownTextDark: 'text-[#d946ef]',
      dropdownTextLight: 'text-[#6b21a8]',
      glow: '#d946ef',
      accentDark: 'bg-[#d946ef]/20',
      accentLight: 'bg-[#9333ea]/20',
      primaryDark: 'text-[#f472b6]',
      primaryLight: 'text-[#9333ea]',
      secondaryDark: 'border-[#f472b6]',
      secondaryLight: 'border-[#9333ea]',
      particleColors: {
        backgroundDark: '#1a103d',
        backgroundLight: '#f3e8ff',
        particleDark: '#d946ef',
        particleLight: '#c600c6',
      },
    },
    neonblue: {
      dark: 'bg-gradient-to-b from-[#0c1e3f] via-[#1e40af] to-[#1e66af]',
      light: 'bg-gradient-to-b from-[#e0f2fe] via-[#e0f2fe] to-[#bae6fd]',
      headerDark: 'bg-gradient-to-r from-[#0c1e3f] via-[#1e40af] to-[#1e66af]',
      headerLight: 'bg-gradient-to-r from-[#e0f2fe] via-[#e0f2fe] to-[#bae6fd]',
      border: 'border-[#38bdf8]',
      textDark: 'text-[#38bdf8]',
      textLight: 'text-[#1e40af]',
      hoverDark: 'hover:text-[#7dd3fc]',
      hoverLight: 'hover:text-[#3b82f6]',
      buttonDark: 'bg-[#1e40af] hover:bg-[#38bdf8]',
      buttonLight: 'bg-[#38bdf8] hover:bg-[#60a5fa]',
      dropdownBgDark: 'bg-[#0c1e3f]',
      dropdownBgLight: 'bg-[#e0f2fe]',
      dropdownBorder: 'border-[#38bdf8]',
      dropdownTextDark: 'text-[#38bdf8]',
      dropdownTextLight: 'text-[#1e40af]',
      glow: '#38bdf8',
      accentDark: 'bg-[#38bdf8]/20',
      accentLight: 'bg-[#3b82f6]/20',
      primaryDark: 'text-[#7dd3fc]',
      primaryLight: 'text-[#3b82f6]',
      secondaryDark: 'border-[#7dd3fc]',
      secondaryLight: 'border-[#3b82f6]',
      particleColors: {
        backgroundDark: '#0c1e3f',
        backgroundLight: '#e0f2fe',
        particleDark: '#38bdf8',
        particleLight: '#1e40af',
      },
    },
    electricpink: {
      dark: 'bg-gradient-to-b from-[#1e0f2f] via-[#431d54] to-[#86198f]',
      light: 'bg-gradient-to-b from-[#fce7f3] via-[#fce7f3] to-[#f9a8d4]',
      headerDark: 'bg-gradient-to-r from-[#1e0f2f] via-[#431d54] to-[#86198f]',
      headerLight: 'bg-gradient-to-r from-[#fce7f3] via-[#fce7f3] to-[#f9a8d4]',
      border: 'border-[#f472b6]',
      textDark: 'text-[#f472b6]',
      textLight: 'text-[#86198f]',
      hoverDark: 'hover:text-[#f9a8d4]',
      hoverLight: 'hover:text-[#d946ef]',
      buttonDark: 'bg-[#86198f] hover:bg-[#f472b6]',
      buttonLight: 'bg-[#f472b6] hover:bg-[#ec4899]',
      dropdownBgDark: 'bg-[#1e0f2f]',
      dropdownBgLight: 'bg-[#fce7f3]',
      dropdownBorder: 'border-[#f472b6]',
      dropdownTextDark: 'text-[#f472b6]',
      dropdownTextLight: 'text-[#86198f]',
      glow: '#f472b6',
      accentDark: 'bg-[#f472b6]/20',
      accentLight: 'bg-[#d946ef]/20',
      primaryDark: 'text-[#f9a8d4]',
      primaryLight: 'text-[#d946ef]',
      secondaryDark: 'border-[#f9a8d4]',
      secondaryLight: 'border-[#d946ef]',
      particleColors: {
        backgroundDark: '#1e0f2f',
        backgroundLight: '#fce7f3',
        particleDark: '#f472b6',
        particleLight: '#86198f',
      },
    },
    cosmicteal: {
      dark: 'bg-gradient-to-b from-[#0f2e33] via-[#0f766e] to-[#115e59]',
      light: 'bg-gradient-to-b from-[#e0f2fe] via-[#ccfbf1] to-[#99f6e4]',
      headerDark: 'bg-gradient-to-r from-[#0f2e33] via-[#0f766e] to-[#115e59]',
      headerLight: 'bg-gradient-to-r from-[#e0f2fe] via-[#ccfbf1] to-[#99f6e4]',
      border: 'border-[#2dd4bf]',
      textDark: 'text-[#2dd4bf]',
      textLight: 'text-[#0f766e]',
      hoverDark: 'hover:text-[#5eead4]',
      hoverLight: 'hover:text-[#14b8a6]',
      buttonDark: 'bg-[#0f766e] hover:bg-[#2dd4bf]',
      buttonLight: 'bg-[#2dd4bf] hover:bg-[#14b8a6]',
      dropdownBgDark: 'bg-[#0f2e33]',
      dropdownBgLight: 'bg-[#ccfbf1]',
      dropdownBorder: 'border-[#2dd4bf]',
      dropdownTextDark: 'text-[#2dd4bf]',
      dropdownTextLight: 'text-[#0f766e]',
      glow: '#2dd4bf',
      accentDark: 'bg-[#2dd4bf]/20',
      accentLight: 'bg-[#14b8a6]/20',
      primaryDark: 'text-[#5eead4]',
      primaryLight: 'text-[#14b8a6]',
      secondaryDark: 'border-[#5eead4]',
      secondaryLight: 'border-[#14b8a6]',
      particleColors: {
        backgroundDark: '#0f2e33',
        backgroundLight: '#ccfbf1',
        particleDark: '#2dd4bf',
        particleLight: '#0f766e',
      },
    },
  };

  return useMemo(() => ({
    colors: colorSchemes[theme as keyof typeof colorSchemes],
    particleColors: colorSchemes[theme as keyof typeof colorSchemes].particleColors,
  }), [theme, isDarkMode]);
};